#!/bin/bash

mount -t sysfs sysfs /sys
mount -t proc proc /proc
mount -t devtmpfs devtmpfs /dev

exec setsid bash </dev/ttyS0 >/dev/ttyS0 2>&1
# exec setsid bash -c "starttsk" </dev/ttyS0 >/dev/ttyS0 2>&1
